x-logging: &default-logging
  driver: loki
  options:
    loki-url: "${LOKI_URL:-http://localhost:3100/loki/api/v1/push}"
    loki-batch-size: "400"
    loki-batch-wait: "1s"
    loki-external-labels: "job=${LOKI_SERVICE:-unknown},service=bms"

x-env: &env
  env_file:
    - ${ENV_FILE:-.env}

services:
  backend:
    <<: [ *env ]
    container_name: bms-backend
    entrypoint: sh -c "alembic upgrade head || true && uvicorn main:app --host 0.0.0.0 --port=80 --log-level=info 2>&1"
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - target: 80
        published: 80
        protocol: tcp
    networks:
      - bms
    profiles: [ "prod" ]
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - BOT_REDIS_DSN=redis://rediska:6379/0
      - LOKI_SERVICE=bms-backend
    logging: *default-logging

  db:
    <<: [ *env ]
    image: postgres:18.1-alpine
    container_name: bms-db
    restart: always
    ports:
      - target: 5432
        published: 6432
        protocol: tcp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bms
    environment:
      - LOKI_SERVICE=db
    logging: *default-logging

  rediska:
    image: redis:8.2.1-alpine
    container_name: bms-redis
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - bms
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
    environment:
      - LOKI_SERVICE=redis
    logging: *default-logging

volumes:
  postgres-data:
    name: bms-db-data
  redis-data:
    name: bms-redis-data

networks:
  bms:
    name: bms
    driver: bridge