version: "3.9"

x-env: &env
  env_file:
    - ${ENV_FILE:-.env}

services:
  backend:
    <<: [ *env ]
    container_name: bms-backend
    entrypoint: sh -c "alembic upgrade head || true && uvicorn main:app --host 0.0.0.0 --port=80 --log-level=critical"
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - target: 80
        published: 80
        protocol: tcp
    networks:
      - bms
    profiles: [ "prod" ]
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - BOT_REDIS_DSN=redis://rediska:6379/0
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=backend"

  db:
    <<: [ *env ]
    image: postgres:18.1-alpine
    container_name: bms-db
    restart: always
    ports:
      - target: 5432
        published: 6432
        protocol: tcp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bms
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=db"

  rediska:
    image: redis:8.2.1-alpine
    container_name: bms-redis
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - bms
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=redis"

  # MONITORING
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - bms

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    networks:
      - bms

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafanadata:/var/lib/grafana
    networks:
      - bms

volumes:
  postgres-data:
    name: bms-db-data
  redis-data:
    name: bms-redis-data

  # MONITORING
  grafanadata:
  prometheusdata:

networks:
  bms:
    name: bms
