x-logging: &default-logging
  driver: loki
  options:
    loki-url: "${LOKI_URL}" 
    loki-batch-size: "400"
    loki-batch-wait: "1s"
    loki-external-labels: "job=bms-backend,service=bms"

x-env: &env
  env_file:
    - ${ENV_FILE:-.env}

services:
  backend:
    <<: [*env]
    container_name: bms-backend
    entrypoint: sh -c "alembic upgrade head || true && uvicorn main:app --host 0.0.0.0 --port=80 --log-level=critical"
    build:
      dockerfile: Dockerfile
    restart: always
    expose:
      - "80"
    networks:
      - proxy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - BOT_REDIS_DSN=redis://rediska:6379/0
      - LOKI_SERVICE=bms-backend
    logging: *default-logging

  db:
    <<: [*env]
    image: postgres:18.1-alpine
    container_name: bms-db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - proxy
    environment:
      - LOKI_SERVICE=db
    logging: *default-logging

  rediska:
    image: redis:8.2.1-alpine
    container_name: bms-redis
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - proxy
    environment:
      - LOKI_SERVICE=redis
    logging: *default-logging

  frontend:
    <<: [*env]
    container_name: bms-frontend
    build:
      context: .
      dockerfile_inline: |
        FROM node:20-alpine AS build
        RUN apk add --no-cache python3 make g++ bash
        WORKDIR /app/frontend
        COPY frontend/ .
        RUN npm install
        RUN npm run build

        FROM nginx:alpine
        COPY --from=build /app/frontend/dist /usr/share/nginx/html
        EXPOSE 80

    restart: always
    expose:
      - "80"
    networks:
      - proxy
    environment:
      - NODE_ENV=production
    logging: *default-logging

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.13.6
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    networks:
      - proxy

volumes:
  postgres-data:
    name: bms-db-data
  redis-data:
    name: bms-redis-data
  npm-data:
    name: npm-data
  npm-letsencrypt:
    name: npm-letsencrypt

networks:
  proxy:
    external: true