x-logging: &default-logging
  driver: loki
  options:
    loki-url: "${LOKI_URL:-http://bms-loki:3100/loki/api/v1/push}"
    loki-batch-size: "400"
    loki-batch-wait: "1s"

x-env: &env
  env_file:
    - ${ENV_FILE:-.env}

services:
  backend:
    <<: [ *env ]
    container_name: bms-backend
    entrypoint: sh -c "alembic upgrade head || true && uvicorn main:app --host 0.0.0.0 --port=80 --log-level=critical"
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - target: 80
        published: 80
        protocol: tcp
    networks:
      - bms
    profiles: [ "prod" ]
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - BOT_REDIS_DSN=redis://rediska:6379/0
    logging: *default-logging

  db:
    <<: [ *env ]
    image: postgres:18.1-alpine
    container_name: bms-db
    restart: always
    ports:
      - target: 5432
        published: 6432
        protocol: tcp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bms
    environment:
      - LOKI_SERVICE=db
    logging: *default-logging

  rediska:
    image: redis:8.2.1-alpine
    container_name: bms-redis
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - bms
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
    environment:
      - LOKI_SERVICE=redis
    logging: *default-logging

  frontend:
    <<: [ *env ]
    container_name: bms-frontend
    build:
      context: .
      dockerfile_inline: |
        FROM node:20-alpine
        WORKDIR /app/frontend
        COPY frontend/ .
        RUN npm ci --silent && npm run build
        EXPOSE 4173
        CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]
    restart: always
    ports:
      - target: 4173
        published: 4173
        protocol: tcp
    networks:
      - bms
    profiles: [ "prod" ]
    environment:
      - NODE_ENV=production
    logging: *default-logging

volumes:
  postgres-data:
    name: bms-db-data
  redis-data:
    name: bms-redis-data

networks:
  bms:
    name: bms
    driver: bridge