global:
  resolve_timeout: 5m

route:
  receiver: "telegram-alerts"
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: "telegram-alerts"
    webhook_configs:
      - url: "http://alertserver:8080/alert"
        send_resolved: true
