global:
  scrape_interval: 5s
  evaluation_interval: 10s
  external_labels:
    cluster: "bms-local"
    environment: "development"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - bms-alertmanager:9093

rule_files:
  - "alerts.yaml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "bms-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["10.130.0.8:8000"]
        labels:
          service: "backend"
          component: "api"

  - job_name: "bms-db"
    static_configs:
      - targets: ["bms-postgres-exporter:9187"]
        labels:
          service: "database"
          component: "db"
