apiVersion: 1
contactPoints:
  - orgId: 1
    name: TG
    receivers:
      - uid: afawtcwpwh9tsa
        type: telegram
        settings:
          bottoken: "${TG_BOT_ALERT_TOKEN}"
          chatid: "${TG_ALERT_CHAT_ID}"
          disable_notification: false
          disable_web_page_preview: false
          parse_mode: Markdown
          protect_content: false
        disableResolveMessage: false
