name: Deploy MONITORING

on:
  workflow_dispatch:

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Monitoring via SSH through Jump Host
        uses: appleboy/ssh-action@v0.1.11
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ secrets.SSH_JUMP_HOST }}
          proxy_username: ${{ secrets.SSH_JUMP_USER }}
          proxy_key: ${{ secrets.SSH_JUMP_PRIVATE_KEY }}
          script: |
            cd /home/volodin_n/booking-management-system/
            git pull
            sudo docker compose -f monitoring/docker-compose.monitoring.yaml up -d --build
